version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: leanstartup-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=leanstartup
    restart: always

volumes:
  mongodb_data: 